;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        delete-region-or-back-char
        keyboard-escape-quit
        paredit-open-round
        previous-buffer
        subword-right
        ))

(setq mc/cmds-to-run-once
      '(
        describe-key-briefly
        eval-last-sexp
        select-word-or-mark-next-like-this
        smex
        ))
